spring.application.name=ezstub-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ezstub
spring.datasource.username=postgres
spring.datasource.password=moe1228?

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#jwt.secret=4f5f4c4d7e2a3b6c8d9e1f2a4b5c6d7e8f9a1b2c3d4e5f6
#jwt.expiration=86400000